apiVersion: v1
kind: Service
metadata:
  name: volunteer-service
  namespace: volunteer-service
spec:
  type: ClusterIP
  selector:
    app: volunteer-service
  ports:
    - port: 8003
      targetPort: 8003
      protocol: TCP
