apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: volunteer-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: solidarytech
  source:
    repoURL: https://github.com/tc-fiap-lacf/fiap-hackathon.git
    targetRevision: main
    path: gitops/apps/volunteer-service
  destination:
    server: https://kubernetes.default.svc
    namespace: volunteer-service
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: ""
      kind: Secret
      jsonPointers:
        - /data