apiVersion: v1
kind: Service
metadata:
  name: ngo-service
  namespace: ngo-service
spec:
  type: ClusterIP
  selector:
    app: ngo-service
  ports:
    - port: 8002
      targetPort: 8002
      protocol: TCP
