name: CI - auth-service 

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ["auth-service/**"]
  pull_request:
    branches: [main]
    paths: ["auth-service/**"]

permissions:
  contents: write

jobs:
  ci:
    uses: ./.github/workflows/_ci-go.yml
    with:
      service_name: auth-service
      service_path: auth-service
      ecr_repository: solidarytech/auth-service
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
